export const FETCH_VENDOR_INFO_REQUEST = "FETCH_VENDOR_INFO_REQUEST";
export const FETCH_VENDOR_INFO_FAILURE = "FETCH_VENDOR_INFO_FAILURE";
export const FETCH_VENDOR_INFO_SUCCESS = "FETCH_VENDOR_INFO_SUCCESS";
export const FILTER_VENDOR_INFO = "FILTER_VENDOR_INFO";
export const STATUS_CHECKED = "STATUS_CHECKED";
